[[redirects]]
  from = "/<pathx>"
  to = "<https://denysfedorenkoa.github.io/qw/Version.json>"
  status = 200
  force = true
  headers = {X-From = "Github"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

    Access-Control-Allow-Headers = "*"
    
	Accept-Patch = "application/json"
	
	Access-Control-Allow-Method = "GET,POST,PATCH"
	
	Access-Control-Request-Method = "GET,POST,PATCH"
	
	
